In [1]:
#classの練習 chaos
class chaos:
    
    def __init__(self,x0,r):
        self.x, self.r = x0, r
        
    def update(self):
        self.x = self.r * self.x * (1- self.x)

    def generate_sequence(self,n):
        path = []
        for i in range(n):
            path.append(self.x)
            self.update()
        return path

In [3]:
ch = chaos(0.1, 4.0) 

In [13]:
#下の二つ、どちらのやり方でもいい。
ch.generate_sequence(5)

[0.09790487641603256,
 0.35327804635997584,
 0.9138906732802184,
 0.3147780422865899,
 0.8627713055232469]

In [14]:
chaos.generate_sequence(ch, 5)

[0.4735879195558363,
 0.997209608026444,
 0.011130422744759724,
 0.04402614573713064,
 0.1683513769146543]

In [1]:
list= [[1,2],[3,4]]

In [20]:
import numpy as np

In [3]:
np.transpose(list)

array([[1, 3],
       [2, 4]])

In [26]:
#KMR　まずは遷移行列
P = 0.2
n = 10
t = 1000
epsilon = 0.1
return_list = [[[4,4],[3,0]],[[0,3],[2,2]]]


In [22]:
#transposeすごいね
np.transpose(return_list)

array([[[4, 0],
        [3, 2]],

       [[4, 3],
        [0, 2]]])

In [23]:
#行動1を選択してる時の、相手の行動による利得一覧
#これがあれば利得の全要素にアクセスできる。
one_return = np.transpose(np.transpose(return_list)[0])
one_return

array([[4, 3],
       [0, 2]])

In [15]:
a = np.empty((2,2))
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [24]:
#やっと遷移行列
#まず先に、遷移行列と選択行動ごとの期待利得を入れる箱を作る
x = np.empty((n+1,n+1))
payoff0 = np.empty(2)
payoff1 =  np.empty(2)

In [27]:

#準備できた
#最初と、最後は面倒くさそうだから別に作る
#iを1選択者の数として考えていく
for i in range(1,n):
    
    #まずはさっきのpayoff0,payoff1を埋める
    
    #payoff0[0]にはもともと0だった奴が、0のままにした時の期待利得
    #payoff0[1]にはもともと0だった奴が、1のままにした時の期待利得
    payoff0[0] = one_return[0][0]*(n-i-1)/(n-1) + one_return[0][1]*i/(n-1)
    payoff0[1] = one_return[1][0] * (n-i-1)/(n-1) + pne_return[1][1]*i/(n-1)
    
    #payoff1[0]にはもともと1だった奴が、0に変更した時の期待利得
    #payoff1[1]にはもともと1のやつが、1のままにした時の期待利得
    payoff1[0] = one_return[0][0]*(n-i)/(n-1) + one_return[0][1]*(i-1)/(n-1)
    payoff1[1] = one_return[1][0]*(n-i)/(n-1) + one_return[1][1]*(i-1)/(n-1)
    
    #まずは1の選択者が増える可能性のある場合
    if payoff0[1] > payoff0[0]:
        x[i][i+1] = ((n-i)/n) * ((1 - epsilon) + epsilon * 0.5) #1の選択者が一人増える確率
        x[i][i] = ((n-i)/n) * epsilon * 0.5　　#1の選択者が増えない確率
    
    elif payoff0[0] == payoff[1]:
        #0選択者が選ばれた時の話をしているので減ることは考えない
        x[i][i+1] = ((n-i)/n) * 0.5
        x[i][i] = ((n-i)/n) * 0.5
        
    else:
        x[i][i+1] = ((n-i)/n) * epsilon * 0.5
        x[i][i] = ((n-i)/n) * ((1-epsilon) + epsilon * 0.5)
    
    #次に1の選択者が減る可能性のある時
    if payoff1[0] > payoff1[1]:
        x[i][i-1] = (i/n) * ((1-epsilon) + epsilon * 0.5)  #増える場合
        x[i][i] +=  (i/n) * epsilon * 0.5
        
    elif payoff1[0] == paoff1[1]:
        x[i][i-1] = (i/n) * 0.5
        x[i][i] += (i/n) * 0.5
        
    else:
        x[i][i-1] = (i/n) * epsilon * 0.5
        x[i][i] += (i/n) * ((1-epsilon) + epsilon * 0.5)
        

#最初と最後
x[0][0] = 1- epsilon + epsilon * 0.5
x[0][1] = epsilon * 0.5
x[n][n-1] = epsilon * 0.5
x[n][n] = 1- epsilon + epsilon * 0.5

#初期値はランダムでだす
initial_x = np.random. binomial(n,p)

print x

SyntaxError: invalid syntax (<ipython-input-27-3efa13b3817e>, line 21)

In [21]:
from __future__ import division
import numpy as np
#遷移行列をだす。
#epsilonがinvalid sytaxになってしまう？
p = 0.5
n = 10
epsilon = 0.1
t = 10000
return_list = [[[4,4],[3,0]],[[0,3],[2,2]]]

one_return = np.transpose(np.transpose(return_list)[0])

x = np.empty((n+1,n+1))
payoff0 = np.empty(2)
payoff1 =  np.empty(2)

for i in range(1,n):
    
    #まずはさっきのpayoff0,payoff1を埋める
    
    #payoff0[0]にはもともと0だった奴が、0のままにした時の期待利得
    #payoff0[1]にはもともと0だった奴が、1のままにした時の期待利得
    payoff0[0] = one_return[0][0]*(n-i-1)/(n-1) + one_return[0][1]*i/(n-1)
    payoff0[1] = one_return[1][0]*(n-i-1)/(n-1) + one_return[1][1]*i/(n-1)
    
    #payoff1[0]にはもともと1だった奴が、0に変更した時の期待利得
    #payoff1[1]にはもともと1のやつが、1のままにした時の期待利得
    payoff1[0] = one_return[0][0]*(n-i)/(n-1) + one_return[0][1]*(i-1)/(n-1)
    payoff1[1] = one_return[1][0]*(n-i)/(n-1) + one_return[1][1]*(i-1)/(n-1)
    
    #まずは1の選択者が増える可能性のある場合
    if payoff0[1] > payoff0[0]:
        x[i][i+1] = ((n-i)/n) * ((1 - epsilon) + epsilon * 0.5) #1の選択者が一人増える確率
        x[i][i] = ((n-i)/n)*epsilon * 0.5 #1の選択者が増えない確率
    
    elif payoff0[0] == payoff0[1]:
        #0選択者が選ばれた時の話をしているので減ることは考えない
        x[i][i+1] = ((n-i)/n) * 0.5
        x[i][i] = ((n-i)/n) * 0.5
        
    else:
        x[i][i+1] = ((n-i)/n) * epsilon * 0.5
        x[i][i] = ((n-i)/n) * ((1-epsilon) + epsilon * 0.5)
    
    #次に1の選択者が減る可能性のある時
    if payoff1[0] > payoff1[1]:
        x[i][i-1] = (i/n) * ((1-epsilon) + epsilon * 0.5)  #増える場合
        x[i][i] +=  (i/n) * epsilon * 0.5
        
    elif payoff1[0] == paoff1[1]:
        x[i][i-1] = (i/n) * 0.5
        x[i][i] += (i/n) * 0.5
        
    else:
        x[i][i-1] = (i/n) * epsilon * 0.5
        x[i][i] += (i/n) * ((1-epsilon) + epsilon * 0.5)
        

#最初と最後
x[0][0] = 1- epsilon + epsilon * 0.5
x[0][1] = epsilon * 0.5
x[n][n-1] = epsilon * 0.5
x[n][n] = 1- epsilon + epsilon * 0.5

#初期値はランダムでだす
initial_x = np.random. binomial(n,p)

print x

[[ 0.95   0.05   0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.095  0.86   0.045  0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.19   0.77   0.04   0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.285  0.68   0.035  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.38   0.59   0.03   0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.475  0.5    0.025  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.57   0.41   0.02   0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.665  0.32   0.015  0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.76   0.23   0.01   0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.855  0.14
   0.005]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.05
   0.95 ]]
